### ISSUE TITLE
Can't enter a task BUG! exception in phase 'semantic analisys' in source unit ...EditTask.groovy

### ISSUE THREAD

**Issue by gverzino63** [gpapp/FreePlaneGTD#112] opened 2020-04-22 14:52 UTC
Hi I installed the add-on on Freeplane portable 1.8.2, created a new mindmap from template with GTD_template.mm, and added an item "* test".

Pushing  F4 or alt-H I get a popup with the error:

![image](https://user-images.githubusercontent.com/64150088/79996688-053e3300-84b9-11ea-9675-a967afb7aa4a.png)

with the old 1.7.x the add-on worked. Any idea  how to fix?

**Comment by gpapp** [comment] 2020-04-22 15:05
Duplicate of #111

**Closed by gpapp** 2020-04-22 15:05 UTC
