### ISSUE TITLE
operation in current Freeplane version

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#117] opened 2021-06-28 14:55 UTC
Hi,

I just tried to run the AddOn on one of the later Freeplane version. But there seem to be problems. I didn't check all combinations, but the ones I checked show different effects:

**FP v1.8.11**
- installation of GTD v3.0.0
- restart of Freeplane, as asked for

**->** after start, a **JAVA error** message appears on the screen. clicking it away.
**->** after choice of "next action list", an **application error** "exception in phase semantic analysis"

**FP v1.9.4**
- installation of GTD v3.6.0-alpha2
- restart of Freeplane, as asked for

**->** there is **no "next action list" entry** within the GTD menu

**Comment by gpapp** [comment] 2021-06-28 18:17
Duplicate of #111
Duplicate of #109

**Closed by gpapp** 2021-06-28 18:17 UTC
