### ISSUE TITLE
Next Action List sidebar layout squeezed

### ISSUE THREAD

**Issue by afrizen** [gpapp/FreePlaneGTD#45] opened 2016-01-25 15:55 UTC
The sidebar of the Next Action list window displays as a thin column (see screen shot) that is not large enough to display its text and just barely useable with contortion.

![screen shot 2016-01-25 at 10 39 02 am](https://cloud.githubusercontent.com/assets/918646/12555871/368f343c-c351-11e5-8251-4cdd63b5d6d6.png)

I'm running Freeplane 1.3.15 on a MBP Retina running  OSX 10.11.2
I reviewed the code and think the issue is in https://github.com/gpapp/FreePlaneGTD/blob/master/src/scripts/FreeplaneGTD.groovy. Someday soon, I will pull the code and send a pull request rather than a bug report (I'm a QA guy, what can I say!)

HTH

**Comment by gpapp** [comment] 2016-01-25 18:42
This is a known issue, that occurs on OSX. Unfortunately I can't lay my hands on any Apple products these days, so I guess it will require someone with Apple devices and programming skills to trace down.

The error is with the display of the reportpanel, that is defined [here](https://github.com/gpapp/FreePlaneGTD/blob/master/src/scripts/FreeplaneGTD.groovy#L170)

I seriously have no clue what could go wrong here, obviously it has something to do with the OSX, as I use the add-on on Linux and Windows without any problems. 

I suspect it's something to do with the SwingBuilder on OSX, and could probably be fixed by adding a few options to one one of the layouts.

**Comment by gpapp** [comment] 2016-01-25 19:59
Ok, this is definitely an osx issue as [detailed here]  (https://developer.apple.com/library/mac/documentation/Java/Conceptual/Java14Development/04-JavaUIToolkits/JavaUIToolkits.html)

**Comment by afrizen** [comment] 2016-01-25 20:33
Ahhh... I was poking around in the right place. 
I've got the hardware, now I just need the time, env, and energy to identify a solution. 

Guess what? I've added it to my FreeplaneGTD list! LOL

BTW, since the upgrade to 1.7.0, I'm getting these four error; are they related in any way:

STDOUT: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDERR: missing key freeplaneGTD_view_project
STDERR: missing key freeplaneGTD_view_who
STDERR: missing key freeplaneGTD_view_context
STDERR: missing key freeplaneGTD_view_when

**Comment by gpapp** [comment] 2016-03-16 10:18
Hi, 

that's a well known issue due to errors in the Freeplane preference system. 

The localized keys of the preferences are found, when the add-on specific preference page is opened, but is not available on the central preference page. On the other hand the add-on specific preference page cannot be saved, due to other issues. I don't feel like fixing it upstream.

**The good news, is that the problem is supposedly gone now, as the whole interface was redesigned.**

Best regards!

**Closed by gpapp** 2016-03-16 10:18 UTC
Labels: bug, help wanted
