### ISSUE TITLE
BUG! exception in phase 'semantic analysys'

### ISSUE THREAD

**Issue by ZbyszekS** [gpapp/FreePlaneGTD#96] opened 2019-04-27 06:56 UTC
Windows 10 home. FreePlane 1.7.7. GTD+ 2.0.1

Ctrl-H results in this:

![image](https://user-images.githubusercontent.com/43908751/56846029-05b5e500-68ca-11e9-99de-2aa309d536e2.png)

I've no idea how to get full report. 
Old GTD 0.8.1 works just fine.

**Comment by gpapp** [comment] 2019-05-06 11:29
Duplicate of #95

**Closed by gpapp** 2019-05-06 11:29 UTC
